name: goreleaser
on: [push, pull_request]
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: goreleaser
      uses: goreleaser/goreleaser-action@master
      with:
        args: release --rm-dist --snapshot